[phases.build]
cmds = ["echo 'Building Django project from subdirectory'"]

[phases.setup]
nixPkgs = ["python312"]

[start]
cmd = "cd Recociliator_J && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT Recociliator_J.wsgi:application"